BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Visitor] (
    [id] NVARCHAR(1000) NOT NULL,
    [name] NVARCHAR(1000) NOT NULL,
    [visitId] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [Visitor_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- AddForeignKey
ALTER TABLE [dbo].[Visitor] ADD CONSTRAINT [Visitor_visitId_fkey] FOREIGN KEY ([visitId]) REFERENCES [dbo].[Visit]([id]) ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
